version: "3.9"

services:
  backend:
    build: ./Back
    container_name: backend
    volumes:
      - ./Back/onsupply_back:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./Front/onsupply_front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Front/onsupply_front:/app
    env_file:
      - .env
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"

volumes:
  postgres_data: