# Generated by Django 5.2.1 on 2025-05-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
