# Generated by Django 5.2.1 on 2025-05-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0002_cartitem_enrollment_favouritecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
